### ISSUE TITLE
求大佬帮助

### ISSUE THREAD

**Issue by BaiMingxu** [reuixiy/reuixiy.github.io#1]
大佬，关于Valine评论，【评论最上面的邮箱和网址是干什么用的？评论的时候填上有什么用么？】
<img width="604" alt="_20181115093920" src="https://user-images.githubusercontent.com/22886455/48524687-51487980-e8bc-11e8-9d4a-6f656c94d167.png">

**Comment by reuixiy** [comment]
## 邮箱

1. 如果 Valine 评论配置了邮件通知，那么回复时，会发一封邮件到这个邮箱通知；
2. 如果用这个邮箱地址注册了 [Gravatar](https://cn.gravatar.com/)，那么头像会显示 Gravatar 的头像。

## 网址

相当于一个友情链接。

**Comment by BaiMingxu** [comment]
谢谢您。

**Comment by BaiMingxu** [comment]
大佬，404页面怎么配置呀？为什么一配置上等下次在重新部署就消失了

**Comment by BaiMingxu** [comment]
大佬，我现在只有文章不是中文的，标签页和分类页面怎么也让他变成不是中文呀？求帮助。
